package dev.symo.actualgenerators.datagen;

import dev.symo.actualgenerators.ActualGenerators;
import dev.symo.actualgenerators.registry.ModBlocks;
import dev.symo.actualgenerators.registry.ModItems;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class ModLanguageProvider extends LanguageProvider {

    public ModLanguageProvider(PackOutput output) {
        super(output, ActualGenerators.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add("itemGroup." + ActualGenerators.MODID + ".main", "Actual Generators");

        add(ModBlocks.CORROSION_CELL.get(), "Corrosion Cell");
        add(ModBlocks.HYDROSTATIC_GENERATOR.get(), "Hydrostatic Generator");
        add(ModBlocks.PHOTOVORE.get(), "Photovore");
        add(ModBlocks.IMPACT_DYNAMO.get(), "Impact Dynamo");
        add(ModBlocks.SPAWNER_SIPHON.get(), "Spawner Siphon");
        add(ModBlocks.ENCHANTMENT_COMBUSTOR.get(), "Enchantment Combustor");
        add(ModBlocks.SURGE_BANK.get(), "Surge Bank");
        add(ModBlocks.CRYSTAL_CHARGER.get(), "Crystal Charger");
        add(ModBlocks.RESONANCE_CRUSHER.get(), "Resonance Crusher");
        add(ModBlocks.LOGIC_PORT.get(), "Logic Port");

        add(ModItems.ENERGY_UPGRADE.get(), "Energy Upgrade");
        add(ModItems.SPEED_UPGRADE.get(), "Speed Upgrade");
        add(ModItems.OVERCLOCK_UPGRADE.get(), "Overclock Upgrade");
        add(ModItems.STACK_UPGRADE.get(), "Stack Upgrade");
        add(ModItems.IRON_TIER_UPGRADE.get(), "Iron Tier Upgrade");
        add(ModItems.GOLD_TIER_UPGRADE.get(), "Gold Tier Upgrade");
        add(ModItems.DIAMOND_TIER_UPGRADE.get(), "Diamond Tier Upgrade");
        add(ModItems.NETHERITE_TIER_UPGRADE.get(), "Netherite Tier Upgrade");
        add("item.actualgenerators.upgrade.energy", "Raises a machine's FE buffer and its transfer rate.");
        add("item.actualgenerators.upgrade.speed", "Runs a machine faster, up to its ceiling. Power cost rises superlinearly.");
        add("item.actualgenerators.upgrade.overclock", "Lets a working machine ramp past its speed ceiling. Power cost rises superlinearly.");
        add("item.actualgenerators.upgrade.stack", "Processes more items per operation instead of more often. Power cost rises linearly \u2014 the efficient way to scale.");
        add("item.actualgenerators.upgrade.install_hint", "Crouch and use on a machine to slot it in");
        add("item.actualgenerators.upgrade.installed", "Installed %s -- now %s / %s");
        add("item.actualgenerators.upgrade.full", "That machine already holds all it will count");
        add("item.actualgenerators.upgrade.refused", "That machine has no use for this upgrade");
        add("item.actualgenerators.tier_upgrade.tooltip", "Machine: speed x%s, batch x%s \u00b7 Pad: amount x%s, delay %st");
        add("item.actualgenerators.tier_upgrade.hint", "Crouch and use on a machine or pad; a higher tier swaps the fitted one out");
        add("item.actualgenerators.tier_upgrade.installed", "Now %s tier");
        add("item.actualgenerators.tier_upgrade.lower", "Already %s tier or better");
        add("item.actualgenerators.tier_upgrade.refused", "Nothing here takes a tier");
        add(ModItems.MACHINE_FRAME.get(), "Machine Frame");
        add(ModItems.IRON_DUST.get(), "Iron Dust");
        add(ModItems.COPPER_DUST.get(), "Copper Dust");
        add(ModItems.GOLD_DUST.get(), "Gold Dust");
        add(ModItems.LINKING_TOOL.get(), "Linking Tool");
        add("item.actualgenerators.linking_tool.hint", "Use on a pad or injector to pick its network");
        add("item.actualgenerators.linking_tool.hint.held", "Held, it shows every pad, its network, the centre and the reach \u00b7 Crouch-use: what it shows");
        add(ModItems.FILTER.get(), "Filter");
        add("item.actualgenerators.filter.blank", "Blank: anything passes");
        add("item.actualgenerators.filter.summary", "Receiving: %s \u00b7 Sending: %s");
        add("item.actualgenerators.filter.hint", "Use to edit. Craft with a blank one to copy, alone to clear");
        add(ModItems.CONFIG_CARD.get(), "Config Card");
        add(ModItems.FLUX_CRYSTAL.get(), "Flux Crystal");
        add(ModItems.FLUX_COUPLER.get(), "Flux Coupler");
        add("item.actualgenerators.flux_coupler.on", "Coupler on");
        add("item.actualgenerators.flux_coupler.off", "Coupler off");
        add("item.actualgenerators.flux_coupler.hint", "Draws on the crystals loaded into it to charge everything else. Use to open");
        add("gui.actualgenerators.coupler.toggle", "Click to switch it over");
        add("gui.actualgenerators.coupler.crystals", "Charge left in the crystals it is holding");

        add("gui.actualgenerators.energy", "Energy: %s / %s FE");
        add("gui.actualgenerators.rate.generating", "+%s FE/t");
        add("gui.actualgenerators.rate.consuming", "-%s FE/t");
        add("gui.actualgenerators.rate.idle", "Idle");
        add("gui.actualgenerators.stored", "Stored: %s FE");
        add("gui.actualgenerators.charge", "Charge: %s%%");
        add("gui.actualgenerators.leaking", "Leaking %s FE/s");
        add("gui.actualgenerators.holding", "Holding");
        add("gui.actualgenerators.mode.charging", "Filling crystals -- click to discharge instead");
        add("gui.actualgenerators.mode.discharging", "Emptying crystals -- click to charge instead");
        add("gui.actualgenerators.progress", "Progress: %s%%");
        add("gui.actualgenerators.progress.idle", "Nothing in progress");
        add("gui.actualgenerators.coupler.progress", "Crystal in hand: %s%% used");
        add("gui.actualgenerators.coupler.left", "%s FE left in it");
        add("gui.actualgenerators.overclock", "Overclock: %s%%");
        add("gui.actualgenerators.overclock.hint", "Ramps up while working, decays only when idle or unpowered");
        add("gui.actualgenerators.warmup", "Warm-up: %s%%");
        add("gui.actualgenerators.warmup.output", "Output: %s%% of rating");
        add("gui.actualgenerators.warmup.hint", "Climbs while it is running, decays when it stops. Never passes the rating");
        add("gui.actualgenerators.side_config", "Side configuration");
        add("gui.actualgenerators.auto.in", "Auto-input: %s");
        add("gui.actualgenerators.auto.out", "Auto-output: %s");
        add("gui.actualgenerators.auto.on", "on");
        add("gui.actualgenerators.auto.off", "off");
        add("gui.actualgenerators.auto.hint", "Whether the machine moves this itself. Faces stay open either way");
        add("gui.actualgenerators.depth", "Depth: %s / %s");
        add("gui.actualgenerators.depth.hint", "Still water standing above the generator");
        add("gui.actualgenerators.output", "%s FE/t");
        add("gui.actualgenerators.food", "Light sources: %s");
        add("gui.actualgenerators.food.hint", "It eats the nearest one first");
        add("gui.actualgenerators.meal", "%s FE per meal");
        add("gui.actualgenerators.impact", "%s FE last impact");
        add("gui.actualgenerators.fell", "Fell %s / %s");
        add("gui.actualgenerators.fell.hint", "Longer drops pay more, up to the cap");
        add("gui.actualgenerators.no_spawner", "No spawner");
        add("gui.actualgenerators.no_spawner.hint", "Place it against one");
        add("gui.actualgenerators.spawn_count", "%s per spawn");
        add("gui.actualgenerators.spawn_delay", "every %st");
        add("gui.actualgenerators.levels", "Levels: %s");
        add("gui.actualgenerators.draw", "Draws %s FE/t");
        add("gui.actualgenerators.frequency", "Frequency: %s Hz");
        add("gui.actualgenerators.frequency.none", "Nothing loaded");
        add("gui.actualgenerators.crusher.tuned", "Tuned");
        add("gui.actualgenerators.crusher.calibrating", "Calibrating");
        add("gui.actualgenerators.crusher.calibrating.hint", "First run on a material takes longer and pays no bonus");
        add("gui.actualgenerators.crusher.batch", "Crushing %s at a time");
        add("gui.actualgenerators.upgrade.installed", "Installed: %s / %s");
        add("gui.actualgenerators.upgrade.next", "→ %s");
        add("gui.actualgenerators.upgrade.maxed", "(max)");
        add("gui.actualgenerators.upgrade.buffer", "Buffer: %s FE %s");
        add("gui.actualgenerators.upgrade.transfer", "Transfer: %s FE/t %s");
        add("gui.actualgenerators.upgrade.speed", "Speed: %sx %s");
        add("gui.actualgenerators.upgrade.overclock", "Peak speed: %sx %s");
        add("gui.actualgenerators.upgrade.batch", "Batch: %s %s");
        add("gui.actualgenerators.upgrade.power", "Power: %sx %s");
        add("gui.actualgenerators.upgrade.yield", "Yield: %s%% %s");
        add("gui.actualgenerators.tier.none", "No tier");
        add("gui.actualgenerators.tier.iron", "Iron");
        add("gui.actualgenerators.tier.gold", "Gold");
        add("gui.actualgenerators.tier.diamond", "Diamond");
        add("gui.actualgenerators.tier.netherite", "Netherite");
        add("gui.actualgenerators.tier.slot", "Tier: %s");
        add("gui.actualgenerators.tier.speed", "Speed: x%s");
        add("gui.actualgenerators.tier.batch", "Batch: x%s");
        add("gui.actualgenerators.tier.hint", "Drop a tier upgrade here, or crouch-use one on the block");
        add("gui.actualgenerators.redstone", "Redstone: %s");
        add("gui.actualgenerators.redstone.always", "Ignored");
        add("gui.actualgenerators.redstone.with_signal", "Needs a signal");
        add("gui.actualgenerators.redstone.without_signal", "Needs no signal");
        add("gui.actualgenerators.redstone.never", "Off");
        add("gui.actualgenerators.mode.disabled", "Disabled");
        add("gui.actualgenerators.mode.input", "Input");
        add("gui.actualgenerators.mode.output", "Output");
        add("gui.actualgenerators.mode.both", "Input and output");
        add("gui.actualgenerators.side.front", "Front");
        add("gui.actualgenerators.side.back", "Back");
        add("gui.actualgenerators.side.left", "Left");
        add("gui.actualgenerators.side.right", "Right");
        add("gui.actualgenerators.side.top", "Top");
        add("gui.actualgenerators.side.bottom", "Bottom");

        add("item.actualgenerators.config_card.copied", "Configuration copied");
        add("item.actualgenerators.config_card.pasted", "Configuration applied");
        add("item.actualgenerators.config_card.empty", "This card is blank -- crouch and use on a machine to copy its setup");
        add("item.actualgenerators.config_card.tooltip.empty", "Blank. Crouch and use on a machine to copy.");
        add("item.actualgenerators.config_card.tooltip.stored", "Holds a machine configuration. Use on a machine to apply.");
        add("item.actualgenerators.config_card.tooltip.pad", "Holds a pad setup, %s links. Use on a pad to apply.");
        add("item.actualgenerators.config_card.tooltip.pad.label", "Holds pad setup \"%s\". Use on a pad to apply.");
        add("item.actualgenerators.config_card.tooltip.clear", "Use at nothing to blank the card");
        add("item.actualgenerators.config_card.pad.copied", "Pad setup copied");
        add("item.actualgenerators.config_card.pad.pasted", "Applied to %s pads");
        add("item.actualgenerators.config_card.pad.missing", "%s got no filter or upgrade: none in your inventory");
        add("item.actualgenerators.config_card.pad.refused", "%s on networks that are not yours");
        add("item.actualgenerators.config_card.pad.machine", "This card holds a machine setup, not a pad's");
        add("item.actualgenerators.config_card.machine.pad", "This card holds a pad setup, not a machine's");
        add("item.actualgenerators.config_card.cleared", "Card blanked");
        add("gui.actualgenerators.card.apply.title", "Apply the pad setup to");
        add("gui.actualgenerators.card.apply.this", "This pad");
        add("gui.actualgenerators.card.apply.flood", "This pad and every touching pad on the same face");

        add(ModItems.LINK_RANGE_UPGRADE.get(), "Link Range Upgrade");
        add("item.actualgenerators.link_range_upgrade.tooltip", "More reach. A full slot also reaches other dimensions");
        add(ModItems.UNBOUND_LINK_CARD.get(), "Unbound Link Card");
        add("item.actualgenerators.unbound_link_card.tooltip", "Unlimited reach in one dimension. One per network");

        add("gui.actualgenerators.link.network", "%s \u00b7 %s pads \u00b7 %s injectors");
        add("gui.actualgenerators.link.unlinked", "No network");
        add("gui.actualgenerators.link.out_of_reach", "out of reach");
        add("gui.actualgenerators.link.network.hint", "Left: pick a network \u00b7 Right: leave it");
        add("gui.actualgenerators.link.range", "Reach: %s blocks from the centre");
        add("gui.actualgenerators.link.range.cross", "Reach: %s blocks, any dimension");
        add("gui.actualgenerators.link.range.unbound", "Reach: unlimited, this dimension");
        add("gui.actualgenerators.link.channel", "%s channel");
        add("gui.actualgenerators.link.channel.hint", "Click: show this channel");
        add("gui.actualgenerators.link.kind.item", "Items");
        add("gui.actualgenerators.link.kind.fluid", "Fluids");
        add("gui.actualgenerators.link.kind.energy", "Energy");
        add("gui.actualgenerators.link.kind.redstone", "Redstone");
        add("gui.actualgenerators.link.kind.none", "Nothing");
        add("gui.actualgenerators.link.carries", "Carries: %s");
        add("gui.actualgenerators.link.carry.on", "%s: carried on this channel");
        add("gui.actualgenerators.link.carry.off", "%s: not carried on this channel");
        add("gui.actualgenerators.link.carry.hint", "Click: carry it, for the whole network \u00b7 Again: stop");
        add("gui.actualgenerators.link.tab.hint", "Click: this kind's settings");
        add("gui.actualgenerators.link.kind_role", "%s: %s");
        add("gui.actualgenerators.link.value.hint", "Click: type it \u00b7 400k, 1.5M, 2B, 64*3 \u00b7 Enter sets, Esc leaves");
        add("gui.actualgenerators.link.cycle.hint", "Left: next \u00b7 Right: previous");
        add("gui.actualgenerators.link.kind.local", "This pad only, until it joins a network");
        add("gui.actualgenerators.link.no_access", "Not yours: the owner has not invited you");
        add("gui.actualgenerators.link.spread.unlinked", "Spread is the network's: join one first");
        add("gui.actualgenerators.link.unlinked.hint", "Set it up now, join later \u00b7 Left: pick a network");
        add("gui.actualgenerators.link.role.sends", "Sends");
        add("gui.actualgenerators.link.role.receives", "Receives");
        add("gui.actualgenerators.link.role.both", "Sends and receives");
        add("gui.actualgenerators.link.role.none", "Not on it");
        add("gui.actualgenerators.link.caption.priority", "Prio");
        add("gui.actualgenerators.link.caption.keep", "Keep");
        add("gui.actualgenerators.link.caption.amount", "Amt");
        add("gui.actualgenerators.link.caption.delay", "Delay");
        add("gui.actualgenerators.link.insert", "Receives: %s");
        add("gui.actualgenerators.link.insert.hint", "Click: toggle \u00b7 This kind, this channel");
        add("gui.actualgenerators.link.extract", "Sends: %s");
        add("gui.actualgenerators.link.extract.hint", "Click: toggle \u00b7 This kind, this channel");
        add("gui.actualgenerators.link.push", "Passes on what is pushed in: %s");
        add("gui.actualgenerators.link.push.hint", "Click: toggle \u00b7 No FE, no Amount, no Delay");
        add("gui.actualgenerators.link.distribution", "Spread: %s");
        add("gui.actualgenerators.link.distribution.hint", "Click: next \u00b7 Nearest, round robin, random, even split");
        add("gui.actualgenerators.link.distribution.nearest_first", "Nearest first");
        add("gui.actualgenerators.link.distribution.round_robin", "Round robin");
        add("gui.actualgenerators.link.distribution.random", "Random");
        add("gui.actualgenerators.link.distribution.even_split", "Even split");
        add("gui.actualgenerators.link.priority", "Priority %s");
        add("gui.actualgenerators.link.priority.hint", "Higher goes first");
        add("gui.actualgenerators.link.keep", "Keep %s");
        add("gui.actualgenerators.link.keep.off", "Keep: off");
        add("gui.actualgenerators.link.keep.hint", "Receiver stops at this many, sender leaves this many");
        add("gui.actualgenerators.link.keep.energy", "Energy has no count");
        add("gui.actualgenerators.link.amount", "Amount: %s per send");
        add("gui.actualgenerators.link.amount.auto", "Amount: %s per send, the tier's limit");
        add("gui.actualgenerators.link.amount.hint", "Most this pad moves in one send, sending or receiving \u00b7 Rate = Amount / Delay");
        add("gui.actualgenerators.link.delay", "Delay: %s ticks (%ss)");
        add("gui.actualgenerators.link.delay.auto", "Delay: %s ticks (%ss), the tier's floor");
        add("gui.actualgenerators.link.delay.hint", "Ticks between this pad's sends \u00b7 A tier upgrade in the pad lowers the floor");
        add("gui.actualgenerators.link.stepper.hint", "Left: 1 \u00b7 Shift or right: 8 \u00b7 Ctrl: 64");
        add("gui.actualgenerators.link.filter.slot", "Filter for this kind on this channel");
        add("gui.actualgenerators.link.filter.slot.hint", "Drop a Filter item here");
        add("gui.actualgenerators.link.filter.slot.stock", "Stock filter for this channel");
        add("gui.actualgenerators.link.filter.slot.stock.hint", "The stock source counts what it lets through \u00b7 Drop a Filter item here");
        add("gui.actualgenerators.link.caption.full", "Full");
        add("gui.actualgenerators.link.full", "Full at %s");
        add("gui.actualgenerators.link.full.off", "Full at: any stock at all");
        add("gui.actualgenerators.link.full.hint", "Stock source: 15 at this many, 1 at the first");
        add("gui.actualgenerators.link.field.redstone", "A level has no such number");
        add("gui.actualgenerators.link.source", "Reads: %s");
        add("gui.actualgenerators.link.source.signal", "the signal the block gives off");
        add("gui.actualgenerators.link.source.comparator", "the block's comparator reading");
        add("gui.actualgenerators.link.source.stock", "the block's stock, against Full");
        add("gui.actualgenerators.link.source.hint", "Left: next \u00b7 Right: previous \u00b7 Signal, comparator, stock");
        add("gui.actualgenerators.link.overlay.reach", "%s \u00b7 reach %s");
        add("gui.actualgenerators.link.overlay.center", "%s \u00b7 centre");
        add("gui.actualgenerators.link.overlay.options", "Linking Tool overlay");
        add("gui.actualgenerators.link.overlay.pads", "Pads and injectors");
        add("gui.actualgenerators.link.overlay.lines", "Centres and lines");
        add("gui.actualgenerators.link.overlay.sphere", "Reach spheres");
        add("gui.actualgenerators.link.overlay.through_walls", "Through walls");
        add("gui.actualgenerators.filter.receive", "Receiving");
        add("gui.actualgenerators.filter.send", "Sending");
        add("gui.actualgenerators.filter.whitelist", "Whitelist");
        add("gui.actualgenerators.filter.blacklist", "Blacklist");
        add("gui.actualgenerators.filter.mode.allow", "Allow");
        add("gui.actualgenerators.filter.mode.block", "Block");
        add("gui.actualgenerators.filter.mode.allow.short", "W");
        add("gui.actualgenerators.filter.mode.block.short", "B");
        add("gui.actualgenerators.filter.mode.allow.tip", "Allow: only what the allowed entries match passes (none: anything)");
        add("gui.actualgenerators.filter.mode.block.tip", "Block: what this matches never passes");
        add("gui.actualgenerators.filter.add", "Add an entry");
        add("gui.actualgenerators.filter.add.tip", "Click: an item, a fluid or a tag");
        add("gui.actualgenerators.filter.add.item", "Item or fluid");
        add("gui.actualgenerators.filter.add.item.tip", "One item, or the fluid in a bucket or tank item");
        add("gui.actualgenerators.filter.add.tag", "Tag");
        add("gui.actualgenerators.filter.add.tag.tip", "Everything under one of an item's tags");
        add("gui.actualgenerators.filter.add.hint", "Left: the item \u00b7 Right: its fluid \u00b7 Or drag from JEI");
        add("gui.actualgenerators.filter.entry.item", "Item entry");
        add("gui.actualgenerators.filter.entry.tag", "Tag entry");
        add("gui.actualgenerators.filter.entry.slot", "Picture");
        add("gui.actualgenerators.filter.entry.slot.empty", "Click here with an item");
        add("gui.actualgenerators.filter.entry.tags.none", "This item has no tags");
        add("gui.actualgenerators.filter.entry.tags.none.empty", "Type a tag above, or click the slot with an item to see its tags");
        add("gui.actualgenerators.filter.entry.tag.box", "Type a tag, Enter sets it");
        add("gui.actualgenerators.filter.entry.tag.box.tip", "c:ingots or #minecraft:logs \u00b7 Enter sets it \u00b7 The rows under are the picture's tags");
        add("gui.actualgenerators.filter.entry.data", "Data");
        add("gui.actualgenerators.filter.entry.data.placeholder", "No data on this entry. Type components here and Apply.");
        add("gui.actualgenerators.filter.entry.data.apply", "Apply");
        add("gui.actualgenerators.filter.entry.data.apply.tip", "Click: the text becomes the entry's data, and Match goes on");
        add("gui.actualgenerators.filter.entry.data.applied", "Applied");
        add("gui.actualgenerators.filter.entry.data.bad", "Not applied: %s");
        add("gui.actualgenerators.filter.marks.both", "Receiving and sending");
        add("gui.actualgenerators.filter.marks.receive", "Receiving only");
        add("gui.actualgenerators.filter.marks.send", "Sending only");
        add("gui.actualgenerators.filter.marks.none", "Counts for nothing yet");
        add("gui.actualgenerators.filter.remove.short", "Remove");
        add("gui.actualgenerators.filter.empty", "No entries: anything passes");
        add("gui.actualgenerators.filter.receive.short", "IN");
        add("gui.actualgenerators.filter.send.short", "EX");
        add("gui.actualgenerators.filter.receive.on", "Counts for what the pad receives");
        add("gui.actualgenerators.filter.receive.off", "Not counted for receiving");
        add("gui.actualgenerators.filter.send.on", "Counts for what the pad sends");
        add("gui.actualgenerators.filter.send.off", "Not counted for sending");
        add("gui.actualgenerators.filter.switch.hint", "Click: toggle");
        add("gui.actualgenerators.filter.remove", "Remove this entry");
        add("gui.actualgenerators.filter.row.hint", "Click: edit");
        add("gui.actualgenerators.filter.nbt", "NBT");
        add("gui.actualgenerators.filter.damaged", "Any damaged item");
        add("gui.actualgenerators.filter.enchanted", "Any enchanted item");
        add("gui.actualgenerators.filter.entry.match", "Match NBT");
        add("gui.actualgenerators.filter.entry.ignore", "Ignore NBT");
        add("gui.actualgenerators.filter.entry.hint", "Match: must carry this data, may carry more");
        add("gui.actualgenerators.filter.entry.back", "Back");
        add("gui.actualgenerators.filter.entry.row.hint", "Click: stand for this tag");
        add("gui.actualgenerators.filter.entry.group", "A tag, mod, damaged or enchanted entry reads no NBT");
        add("gui.actualgenerators.filter.tag", "Any %s");
        add("gui.actualgenerators.filter.mod", "Any from %s");
        add("gui.actualgenerators.picker.title.pad", "%s pad: pick a network");
        add("gui.actualgenerators.picker.title.injector", "Injector: pick a network");
        add("gui.actualgenerators.picker.name", "Name");
        add("gui.actualgenerators.picker.create", "Create");
        add("gui.actualgenerators.picker.leave", "Leave");
        add("gui.actualgenerators.picker.row", "%s pads \u00b7 %s inj");
        add("gui.actualgenerators.picker.empty", "No networks yet. Name one and create it.");
        add("gui.actualgenerators.picker.colour", "Colour: %s");
        add("gui.actualgenerators.picker.colour.hint", "Paints the network this block is on");
        add("gui.actualgenerators.picker.row.hint", "Click: put this block on it");
        add("gui.actualgenerators.picker.view", "Overview");
        add("gui.actualgenerators.picker.view.hint", "Click: every pad, injector and channel \u00b7 Joins nothing");
        add("gui.actualgenerators.picker.delete", "Delete this network");
        add("gui.actualgenerators.picker.delete.hint", "Click: forget it, with its channels, colour and labels");
        add("gui.actualgenerators.picker.delete.owner", "The owner's to delete");
        add("gui.actualgenerators.picker.delete.full", "Still has %s pads \u00b7 %s inj: empty it first");
        add("gui.actualgenerators.overview.channels", "Channels");
        add("gui.actualgenerators.overview.channels.none", "No channel carries anything yet");
        add("gui.actualgenerators.overview.channel.counts", "%s\u25b2 %s\u25bc");
        add("gui.actualgenerators.overview.channel.counts.tip", "%s sending, %s receiving, of the loaded pads");
        add("gui.actualgenerators.overview.pads", "Pads (%s)");
        add("gui.actualgenerators.overview.pad.unloaded", "Unloaded");
        add("gui.actualgenerators.overview.pad.reach", "Reach %s \u00b7 in reach");
        add("gui.actualgenerators.overview.pad.out", "Reach %s \u00b7 out of reach");
        add("gui.actualgenerators.overview.pad.idle", "Nothing switched on");
        add("gui.actualgenerators.overview.link.sends", "sends");
        add("gui.actualgenerators.overview.link.receives", "receives");
        add("gui.actualgenerators.overview.link.door", "door");
        add("gui.actualgenerators.overview.injectors", "Injectors (%s)");
        add("gui.actualgenerators.overview.injectors.none", "No injector: nothing moves");
        add("gui.actualgenerators.overview.injector.energy", "%s / %s FE");
        add("gui.actualgenerators.overview.injector.tip", "%s of %s FE");
        add("gui.actualgenerators.overview.centre", "Centre %s %s %s");
        add("gui.actualgenerators.overview.back", "Back");
        add("gui.actualgenerators.overview.row.hint", "Click: flash it in the world for 7 s");
        add("gui.actualgenerators.overview.row.flashing", "Flashing in the world now");
        add("gui.actualgenerators.link.label", "Label");
        add("gui.actualgenerators.link.label.empty", "Label\u2026");
        add("gui.actualgenerators.link.label.hint", "Click: type one, or pick one the network knows \u00b7 Same label, same settings");
        add("gui.actualgenerators.link.label.pull", "Take its settings");
        add("gui.actualgenerators.link.label.push", "Push mine to it");
        add("gui.actualgenerators.link.label.exists", "\"%s\" is on this network:");
        add("gui.actualgenerators.link.label.none", "No labels on this network yet");
        add("gui.actualgenerators.link.label.nomatch", "No label starts like that");
        add("gui.actualgenerators.link.label.banner.filters", "%s pads lack a filter");
        add("gui.actualgenerators.link.label.banner.upgrades", "%s pads lack an upgrade");
        add("gui.actualgenerators.link.label.banner.hint", "None in your inventory to give them \u00b7 Click: dismiss");
        add("gui.actualgenerators.link.export", "Export");
        add("gui.actualgenerators.link.export.hint", "Click: this pad's setup as text, to the clipboard");
        add("gui.actualgenerators.link.import", "Import");
        add("gui.actualgenerators.link.import.hint", "Click: apply the setup on the clipboard to this pad");
        add("gui.actualgenerators.link.export.done", "Pad setup copied to the clipboard");
        add("gui.actualgenerators.link.import.bad", "The clipboard does not hold a pad setup");
        add("gui.actualgenerators.link.import.done", "Pad setup applied");
        add("gui.actualgenerators.facing.short.north", "N");
        add("gui.actualgenerators.facing.short.south", "S");
        add("gui.actualgenerators.facing.short.east", "E");
        add("gui.actualgenerators.facing.short.west", "W");
        add("gui.actualgenerators.facing.short.up", "U");
        add("gui.actualgenerators.facing.short.down", "D");
        add("gui.actualgenerators.picker.owner", "Owner: %s");
        add("gui.actualgenerators.picker.owner.none", "Nobody's");
        add("gui.actualgenerators.picker.claim", "Claim");
        add("gui.actualgenerators.picker.claim.tip", "Nobody's yet: anyone may run it");
        add("gui.actualgenerators.picker.claim.hint", "Click: make it yours, and private");
        add("gui.actualgenerators.picker.owner.only", "The owner's to change");
        add("gui.actualgenerators.picker.shared.public", "Public");
        add("gui.actualgenerators.picker.shared.private", "Private");
        add("gui.actualgenerators.picker.shared.public.tip", "Public: anyone may put a block on it");
        add("gui.actualgenerators.picker.shared.private.tip", "Private: the owner and the invited only");
        add("gui.actualgenerators.picker.shared.hint", "Click: switch");
        add("gui.actualgenerators.picker.invite", "Invite");
        add("gui.actualgenerators.picker.invite.name", "Player name");
        add("gui.actualgenerators.picker.invite.tip", "Lets a player see, join and set up this network");
        add("gui.actualgenerators.picker.invite.hint", "Type a name \u00b7 Enter or click");
        add("gui.actualgenerators.picker.members.none", "Nobody invited");
        add("gui.actualgenerators.picker.member.remove", "Remove %s");
        add("gui.actualgenerators.picker.member.remove.hint", "Click: off the network \u00b7 Their pads come off with them");
        add("gui.actualgenerators.picker.member.transfer", "Make %s the owner");
        add("gui.actualgenerators.picker.member.transfer.hint", "Click: hand the network over \u00b7 You stay invited");
        add("jade.actualgenerators.link.pad", "%s pad: %s");
        add("jade.actualgenerators.link.pad.unlinked", "%s pad: no network");
        add("jade.actualgenerators.link.channel", "  %s: %s %s");
        add("jade.actualgenerators.link.signal", "  Redstone out: %s");

        add("block.actualgenerators.logic_port.face", "%s pad");
        add("gui.actualgenerators.facing.north", "North");
        add("gui.actualgenerators.facing.south", "South");
        add("gui.actualgenerators.facing.east", "East");
        add("gui.actualgenerators.facing.west", "West");
        add("gui.actualgenerators.facing.up", "Up");
        add("gui.actualgenerators.facing.down", "Down");

        add("block.actualgenerators.energy_injector", "Energy Injector");
        add("gui.actualgenerators.injector.serving", "Paying for %s pads");

        // Jade, when it is installed. The category name is what its own settings screen shows.
        add("config.jade.plugin_actualgenerators.machine", "Machine status");
        add("config.jade.plugin_actualgenerators.logic_port", "Logic Port status");
        add("jade.actualgenerators.progress", "Progress: %s%%");
        add("jade.actualgenerators.overclock", "Overclock: %s%% (%sx)");
        add("jade.actualgenerators.warmup", "Warm-up: %s%% (%s%% of rating)");
        add("jade.actualgenerators.tuned", "Tuned to %s Hz");
        add("jade.actualgenerators.calibrating", "Calibrating %s Hz");

        // JEI, likewise.
        add("jei.actualgenerators.flux_crystal",
                "A battery in item form. Any machine or charger that takes a battery takes one of these, "
                        + "so energy can be crafted, stored on a shelf, or piped around as an item.");
        add("jei.actualgenerators.linking_tool",
                "Use on a Logic Port pad or an Energy Injector to put it on a network: name a new one or pick "
                        + "one from the list. Held, it shows every pad in view, its network, and the network's centre.");
        add("jei.actualgenerators.filter",
                "Two lists: what passes, and what never does. Set it up by using it, then drop it into a "
                        + "pad's filter slot. Craft it with a blank Filter to copy it, alone to clear it.");
    }
}
